### ISSUE TITLE
Just preview

### ISSUE THREAD

**Issue by Murzetskyyy** [Murzetskyy/ftg-modules#1]
![Buckshot Roulette Hu Tao Render](https://github.com/user-attachments/assets/09deb63f-3a85-4c6b-b95f-d236afce5050)

**Comment by p1k0chu** [comment]
це і є ваша backshots roulette?

**Comment by Murzetskyyy** [comment]
> це і є ваша backshots roulette?

так 
https://github.com/user-attachments/assets/8f072bef-1958-446b-b5ab-ed9901025b17
